server:
  port: 1000
eureka:
  client:
    service-url:
#      对外公开的地址，用以将注册中心客户端的信息注册到此处
      defaultZone: http://localhost:1000/eureka/
#      是否获取注册中心服务端的信息，自己没必要获取自己
    fetch-registry: false
#    是否将信息保存到注册中心服务端，自己没必要保存自己
    register-with-eureka: false

